// Generated by CoffeeScript 1.8.0
var mesa;

mesa = require('../src/mesa');

module.exports = {
  'attached function is called with this': function(test) {
    var query;
    query = mesa.clone();
    query.attached = function() {
      test.equal(this, query);
      return test.done();
    };
    return (function() {
      return query.attached();
    })();
  }
};
